import { ClubPosition } from './club-position.model';

export const CLUB_POSITIONS: Array<ClubPosition> =
	 [
		{
			position: 1,
			lastPosition: 1,
			club: 'Manchester City',
			won: 6,
			drawn: 0,
			lost: 2,
			goalFor: 19,
			goalAgainst: 7,
			points: 18,
			comment: ''
		},
		{
			position: 2,
			lastPosition: 6,
			club: 'Arsenal',
			won: 5,
			drawn: 1,
			lost: 2,
			goalFor: 13,
			goalAgainst: 7,
			points: 16,
			comment: ''
		},
		{
			position: 3,
			lastPosition: 2,
			club: 'Manchester United',
			won: 5,
			drawn: 1,
			lost: 2,
			goalFor: 12,
			goalAgainst: 8,
			points: 16,
			comment: ''
		},
		{
			position: 4,
			lastPosition: 3,
			club: 'Crystal Palace',
			won: 5,
			drawn: 0,
			lost: 3,
			goalFor: 11,
			goalAgainst: 7,
			points: 15,
			comment: ''
		},
		{
			position: 5,
			lastPosition: 4,
			club: 'Leicester City',
			won: 4,
			drawn: 3,
			lost: 1,
			goalFor: 17,
			goalAgainst: 15,
			points: 15,
			comment: ''
		},
		{
			position: 6,
			lastPosition: 5,
			club: 'West Ham United',
			won: 4,
			drawn: 2,
			lost: 2,
			goalFor: 17,
			goalAgainst: 11,
			points: 14,
			comment: ''
		},
		{
			position: 7,
			lastPosition: 7,
			club: 'Everton',
			won: 3,
			drawn: 4,
			lost: 1,
			goalFor: 12,
			goalAgainst: 8,
			points: 13,
			comment: ''
		},
		{
			position: 8,
			lastPosition: 8,
			club: 'Tottanham Hotspurs',
			won: 3,
			drawn: 4,
			lost: 1,
			goalFor: 11,
			goalAgainst: 7,
			points: 13,
			comment: '' 
		},{
			position: 9,
			lastPosition: 9,
			club: 'Southampton',
			won: 3,
			drawn: 3,
			lost: 2,
			goalFor: 13,
			goalAgainst: 10,
			points: 12,
			comment: ''
		},
		{
			position: 10,
			lastPosition: 10,
			club: 'Liverpool',
			won: 3,
			drawn: 3,
			lost: 2,
			goalFor: 8,
			goalAgainst: 10,
			points: 12,
			comment: ''
		},
		{
			position: 11,
			lastPosition: 12,
			club: 'Swansea City',
			won: 2,
			drawn: 4,
			lost: 2,
			goalFor: 10,
			goalAgainst: 10,
			points: 10,
			comment: ''
		},
		{
			position: 12,
			lastPosition: 11,
			club: 'Watford',
			won: 2,
			drawn: 4,
			lost: 2,
			goalFor: 6,
			goalAgainst: 7,
			points: 10,
			comment: ''
		},
		{
			position: 13,
			lastPosition: 13,
			club: 'Norwich City',
			won: 2,
			drawn: 3,
			lost: 3,
			goalFor: 12,
			goalAgainst: 14,
			points: 9,
			comment: ''
		},
		{
			position: 14,
			lastPosition: 14,
			club: 'Stoke City',
			won: 2,
			drawn: 3,
			lost: 3,
			goalFor: 8,
			goalAgainst: 10,
			points: 9,
			comment: ''
		},
		{
			position: 15,
			lastPosition: 15,
			club: 'Bournemouth',
			won: 2,
			drawn: 2,
			lost: 4,
			goalFor: 10,
			goalAgainst: 12,
			points: 8,
			comment: ''
		},
		{
			position: 16,
			lastPosition: 16,
			club: 'Chelsea',
			won: 2,
			drawn: 2,
			lost: 4,
			goalFor: 12,
			goalAgainst: 17,
			points: 8,
			comment: ''
		},
		{
			position: 17,
			lastPosition: 17,
			club: 'West Bromwich Albion',
			won: 2,
			drawn: 2,
			lost: 4,
			goalFor: 6,
			goalAgainst: 11,
			points: 8,
			comment: ''
		},
		{
			position: 18,
			lastPosition: 18,
			club: 'Aston Villa',
			won: 1,
			drawn: 1,
			lost: 6,
			goalFor: 8,
			goalAgainst: 13,
			points: 4,
			comment: ''
		},
		{
			position: 19,
			lastPosition: 19,
			club: 'Sunderland',
			won: 0,
			drawn: 3,
			lost: 5,
			goalFor: 8,
			goalAgainst: 18,
			points: 3,
			comment: ''
		},{
			position: 20,
			lastPosition: 20,
			club: 'Newcastle United',
			won: 0,
			drawn: 3,
			lost: 5,
			goalFor: 6,
			goalAgainst: 17,
			points: 3,
			comment: ''
		}
	]